#!/bin/bash

file=$1

#-------------------------------------------------------------------
# create dir
mkdir -p .condor/

#-------------------------------------------------------------------
# base filename
#file_condor_base="${file%.*}"
args="$*"
args=${args// /_} 
args=${args//-/_} 
args=${args//\//_} 
file_condor_base=$args

#-------------------------------------------------------------------
# create condor config
condor_task=.condor/${file_condor_base}.sub

#-------------------------------------------------------------------
if [ -f condor.cfg ];
then
    echo "condor.cfg exists."
    cp condor.cfg ${condor_task} 
else
   echo "condor.cfg does not exist, creating default"
#::::::::::::::::::::::::::::::::::::::::::
cat > ${condor_task}  << EOF

universe              = vanilla
notification          = Never 
#nice_user             = True
getenv                = True
request_cpus          = 1
request_gpus          = 1
request_memory        = 2000 
should_transfer_files = no

EOF
#::::::::::::::::::::::::::::::::::::::::::
fi
echo "requirements   = TARGET.Machine == \"${HOSTNAME}\"" >> ${condor_task}

#-------------------------------------------------------------------

#::::::::::::::::::::::::::::::::::::::::::
cat >> ${condor_task} << EOF
executable = `which ${file}` 
arguments  = ${@:2}
output     = .condor/${file_condor_base}.log
error      = .condor/${file_condor_base}.err
log        = .condor/${file_condor_base}.clog
queue

EOF
#::::::::::::::::::::::::::::::::::::::::::

#-------------------------------------------------------------------
# view the condor config

#cat ${condor_task}

#-------------------------------------------------------------------
# launch condor job

_condor_submit.sh --sync y --config ${condor_task} 


#-------------------------------------------------------------------
# log
cat .condor/${file_condor_base}.log

#-------------------------------------------------------------------
# clean

#rm -rf .condor/

