#!/bin/bash

file=$1
n_jobs=${@: -1}

#-------------------------------------------------------------------
# create dir
mkdir -p .condor/

#-------------------------------------------------------------------
# base filename
#file_condor_base="${file%.*}"
args="$*"
args=${args// /_} 
args=${args//-/_} 
args=${args//\//_} 

file_condor_base=$args

#-------------------------------------------------------------------
# create condor config

condor_task=.condor/${file_condor_base}.sub

#::::::::::::::::::::::::::::::::::::::::::
cat > ${condor_task} << EOF

executable = `which ${file}`
arguments  = ${@:2} \$(icluster)
output     = .condor/${file_condor_base}_\$(ifile).log
error      = .condor/${file_condor_base}_\$(ifile).err
log        = .condor/${file_condor_base}.clog

EOF
#::::::::::::::::::::::::::::::::::::::::::

for((i=0;i<$n_jobs;i++)); do
	  ifile=`echo $i | awk '{ printf("%03d",$1);}'`
      echo "
      ifile = $ifile
      icluster = $i
      queue " 
done >> ${condor_task}

#-------------------------------------------------------------------
# view the condor config

#cat ${condor_task}

#-------------------------------------------------------------------
# launch condor job

_condor_submit.sh --sync y --config ${condor_task} 


#-------------------------------------------------------------------
# clean

#rm -rf .condor


