#!/bin/bash

#-------------------------------------------------------------------
# parse --block/--noblock (default: --block)
BLOCK_MODE="block"
if [[ "$1" == "--noblock" ]]; then
    BLOCK_MODE="noblock"
    shift
elif [[ "$1" == "--block" ]]; then
    BLOCK_MODE="block"
    shift
fi

file=$1

list=${@: -1}

n_jobs=`wc -l ${list} | awk '{ print $1 }'`

#-------------------------------------------------------------------
# create dir
mkdir -p .condor/

#-------------------------------------------------------------------
# base filename
#file_condor_base="${file%.*}"
args="$*"
args=${args// /_} 
args=${args//-/_} 
args=${args//\//_} 

file_condor_base=$args

#-------------------------------------------------------------------
# lock check: warn if a previous job with the same name is still running
lock_file=.condor/${file_condor_base}.lock
clog_file=.condor/${file_condor_base}.clog
if [[ -f "$lock_file" ]]; then
    if [[ -f "$clog_file" ]] && grep -qE '^005|^009' "$clog_file"; then
        echo "Previous job finished. Removing stale lock."
        rm -f "$lock_file"
    else
        echo -e "\e[1;31mWARNING: A job with the same name is already running or queued!\e[0m"
        echo -e "\e[1;31mLock file: $lock_file\e[0m"
        echo -e "\e[1;33mIf the previous job is no longer running, remove the lock manually:\e[0m"
        echo -e "\e[1;33m  rm $lock_file\e[0m"
        exit 1
    fi
fi

#-------------------------------------------------------------------
# create condor config

condor_task=.condor/${file_condor_base}.sub

#::::::::::::::::::::::::::::::::::::::::::
cat > ${condor_task} << EOF

executable = `which ${file}`
arguments  = ${@:2:${#}-2} \$(iline)
output     = .condor/${file_condor_base}_\$(ifile).log
error      = .condor/${file_condor_base}_\$(ifile).err
log        = .condor/${file_condor_base}.clog

EOF
#::::::::::::::::::::::::::::::::::::::::::

for((i=0;i<$n_jobs;i++)); do
	  ifile=`echo $i | awk '{ printf("%03d",$1);}'`
      echo "
      iline = `sed "$(( i + 1 ))q;d" $list`
      ifile = $ifile
      queue " 
done >> ${condor_task}

#-------------------------------------------------------------------
# view the condor config

cat ${condor_task}

#-------------------------------------------------------------------
# clean old condor log so condor_wait doesn't see stale events
rm -f .condor/${file_condor_base}.clog

#-------------------------------------------------------------------
# create lock file
touch "$lock_file"

#-------------------------------------------------------------------
# launch condor job

if [[ "$BLOCK_MODE" == "block" ]]; then
    _condor_submit.sh --sync y --config ${condor_task}
    rm -f "$lock_file"
else
    _condor_submit.sh --config ${condor_task}
fi


